openapi: 3.0.2
info:
  title: Pokemon Open Data API
  version: "1.0"
servers:
  - url: http://localhost:8080/api/v1

paths:
  /pokemon:
    get:
      summary: ポケモン 一覧
      description: ポケモンの一覧を取得する
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'

components:
  parameters:
    AcceptHeader:
      name: accept
      in: header
      description: Request header for content type
      required: false
      schema:
        type: string
        enum:
          - application/json
        default: application/json

  schemas:
    Pokemon:
      type: object
      properties:
        id:
          type: string
          format: uuid
        number:
          type: integer
          minimum: 1
          maximum: 65535
        name:
          type: string
        englishName:
          type: string
        type1:
          $ref: '#/components/schemas/Type'
        type2:
          nullable: true
          $ref: '#/components/schemas/Type'
      required:
        - id
        - number
        - name
        - englishName
        - type1
        - type2
    Type:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name

