services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    tty: true
    ports:
      - "3000:3000"

  web:
    build: ./web
    ports:
      - "8080:80"

  client:
    build: ./client
    volumes:
      - ./client:/app
    tty: true
    ports:
      - "5173:5173"

  migration:
    build: ./import
    volumes:
      - ./import:/app
    
  mysql:
    build: ./database
    env_file:
      - ./database/.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - db-data:/var/lib/mysql
      
volumes:
  db-data:
