CREATE TABLE
    opendata (
        id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(100) NOT NULl,
        japanese_name VARCHAR(100) NOT NULL,
        pokedex_number SMALLINT UNSIGNED NOT NULL,
        generation TINYINT UNSIGNED NOT NULL,
        type1 VARCHAR(10) NOT NULL,
        type2 VARCHAR(10) NULL,
        base_total SMALLINT UNSIGNED NOT NULL,
        hp TINYINT UNSIGNED NOT NULL,
        attack TINYINT UNSIGNED NOT NULL,
        defense TINYINT UNSIGNED NOT NULL,
        sp_attack TINYINT UNSIGNED NOT NULL,
        sp_defense TINYINT UNSIGNED NOT NULL,
        speed TINYINT UNSIGNED NOT NULL,
        abilities TEXT NOT NULL,
        base_egg_steps SMALLINT UNSIGNED NOT NULL,
        base_happiness TINYINT UNSIGNED NOT NULL,
        capture_rate TINYINT UNSIGNED NOT NULL,
        classfication VARCHAR(100) NOT NULL,
        experience_growth INT UNSIGNED,
        percentage_male DECIMAL(4, 1) NULL,
        height_m DECIMAL(2, 1) UNSIGNED NULL,
        weight_kg DECIMAL(4, 1) UNSIGNED NULL,
        is_legendary BOOLEAN NOT NULL DEFAULT FALSE,
        against_bug DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_dark DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_dragon DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_electric DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_fairy DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_fight DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_fire DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_flying DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_ghost DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_grass DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_ground DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_ice DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_normal DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_poison DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_psychic DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_rock DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_steel DECIMAL(3, 2) UNSIGNED NOT NULL,
        against_water DECIMAL(3, 2) UNSIGNED NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
